version: "3.9"

services:
  questdb:
    image: questdb/questdb:latest
    container_name: qdb_metrics_questdb
    restart: always
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9009:9009"
      - "9003:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - QDB_METRICS_ENABLED=TRUE
    volumes:
      - ./questdb_root:/var/lib/questdb/

  grafana:
    image: grafana/grafana-oss
    container_name: qdb_metrics_grafana
    restart: always
    user: "${DOCKER_COMPOSE_USER_ID:-}"
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - questdb
    volumes:
      - ./grafana/home_dir/var_lib_grafana:/var/lib/grafana/
      - ./grafana/home_dir/etc_grafana:/etc/grafana/
    environment:
      - GF_INSTALL_PLUGINS=questdb-questdb-datasource
      - QDB_CLIENT_METADATA_HOST=${QDB_CLIENT_METADATA_HOST:-questdb}
      - QDB_CLIENT_METADATA_PORT=${QDB_CLIENT_METADATA_PORT:-8812}
      - QDB_CLIENT_METADATA_USER=${QDB_CLIENT_METADATA_USER:-admin}
      - QDB_CLIENT_METADATA_PASSWORD=${QDB_CLIENT_METADATA_PASSWORD:-quest}
      # use the value "disable" for local installations, and "require" for QuestDB Cloud
      - QDB_METADATA_SSL_MODE=${QDB_METADATA_SSL_MODE:-disable}
      - QDB_CLIENT_HOST=${QDB_CLIENT_HOST:-questdb}
      - QDB_CLIENT_PORT=${QDB_CLIENT_PORT:-8812}
      - QDB_CLIENT_USER=${QDB_CLIENT_USER:-admin}
      - QDB_CLIENT_PASSWORD=${QDB_CLIENT_PASSWORD:-quest}
      # use the value "disable" for local installations, and "require" for QuestDB Cloud
      - QDB_SSL_MODE=${QDB_SSL_MODE:-disable}

  telegraf:
    image: telegraf
    container_name: qdb_metrics_telegraf
    depends_on:
      - questdb
    volumes:
      - ./telegraf/questdb_metrics_telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
      - QUESTDB_METRICS_ENDPOINT=${QUESTDB_METRICS_ENDPOINT:-http://questdb:9003/metrics}
      - QUESTDB_HTTP_ENDPOINT=${QUESTDB_HTTP_ENDPOINT:-http://questdb:9000}
      - QUESTDB_HTTP_TOKEN=${QUESTDB_HTTP_TOKEN:-}
      - QUESTDB_SKIP_TLS_VERIFICATION=${QUESTDB_SKIP_TLS_VERIFICATION:-true}



